# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CococaPods' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CococaPods
  pod 'SwiftyJSON', '~> 4.0'
#  pod 'Alamofire', '~> 4.0.0-rc.2'
  pod 'AnimationSugar', '~> 0.0.2'
end
